name: CryptoWebhook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # 매일 06:00 KST (다음 날)

jobs:
  cronjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: |
          cd scheduling
          npm install

      - name: Inspect daily asset prices
        env:
          DISCORD_FINANCIAL_ASSET_INDEX: ${{ secrets.DISCORD_FINANCIAL_ASSET_INDEX }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          API_NINJAS_API_KEY: ${{ secrets.API_NINJAS_API_KEY }}
        run: cd scheduling && node --experimental-strip-types ./src/cryptocurrency.ts
